
name: Transfer src folder

on:
  push:
    branches:
      - main

jobs:
  transfer-src:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Archive src folder
      run: tar -czf src.tar.gz src

    - name: Copy via SCP with SSH key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SCP_HOST }}
        username: ${{ secrets.SCP_USERNAME }}
        password: ${{ secrets.SCP_PASSWORD }}
        source: "src.tar.gz"
        target: "~/src"

    - name: Unpack archive
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SCP_HOST }}
        username: ${{ secrets.SCP_USERNAME }}
        password: ${{ secrets.SCP_PASSWORD }}
        script: |
          tar -xzf src/src.tar.gz
          rm -rf src/src.tar.gz

    # - name: Stop Old docker compose
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.SCP_HOST }}
    #     username: ${{ secrets.SCP_USERNAME }}
    #     password: ${{ secrets.SCP_PASSWORD }}
    #     script: |
    #       docker stop $(docker ps -qa)
    #       docker rm $(docker ps -qa)

    - name: Start Docker compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SCP_HOST }}
        username: ${{ secrets.SCP_USERNAME }}
        password: ${{ secrets.SCP_PASSWORD }}
        script: docker compose --profile=prod -f src/docker-compose.yaml up -d

