name: Deploy and Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
          chmod 400 ssh_key.pem

      - name: Copy Files to Remote Instance
        run: scp -i ssh_key.pem -o StrictHostKeyChecking=no -r ./src ubuntu@3.81.60.8:~

      - name: SSH into Remote Instance and Run Docker Compose
        run: |
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@3.81.60.8 << 'EOF'
            cd /src
            docker-compose up -d
          EOF
